### ISSUE TITLE
Bug when not using the default wp-content location

### ISSUE THREAD

**Issue by Xayer** [inboundnow/retired-leads#181]
Hello.

In `shared/shortcodes/shortcodes-fields.php` on line 9. you are hardcoding the wp content folder. You should be using the `CONTENT_DIR` constant defined in wp-config.

So the code should be written a little like so:

```
/*  Include wp-load
    *   ----------------------------------------------------- */
    /*  Include wp-load
    *   ----------------------------------------------------- */
    $path_to_file = explode( CONTENT_DIR, __FILE__ );
    $path_to_wp = $path_to_file[0];
.......
```

**Comment by atwellpub** [comment]
Thank you have the change added in. Will monitor it for performance and let it live in the next update.

**Comment by Xayer** [comment]
@atwellpub I'm not entirely certain that the exact piece of code will work on practice, or that it's the right constant that I've used. But it should guide you in the right direction at least.

**Comment by atwellpub** [comment]
Thanks for that warning. When I tested this is what I ended up using:

```
/* 	Include wp-load
	* 	----------------------------------------------------- */
	$path_to_wp =  get_home_path();
	require_once( $path_to_wp . '/wp-load.php' );
```

**Comment by Xayer** [comment]
@atwellpub yes, exactly. Glad to be of service 👍
